version: "2"

linters:
  default: standard
  enable:
    - exhaustive
    - testifylint
    - errorlint
    - gocritic
    - gosec
    - prealloc
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - gosec
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    testifylint:
      enable-all: true

formatters:
  enable:
    - gofmt
    - goimports
